export enum ErrorCode {
  MISSING_AUTH_HEADER = "MISSING_AUTH_HEADER",
  INVALID_TOKEN = "INVALID_TOKEN",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_LINKED = "EMAIL_ALREADY_LINKED",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  ADMIN_REQUIRED = "ADMIN_REQUIRED",

  USER_NOT_FOUND = "USER_NOT_FOUND",
  ADMIN_GRANT_NOT_FOUND = "ADMIN_GRANT_NOT_FOUND",
  LAST_ADMIN_REMOVAL_FORBIDDEN = "LAST_ADMIN_REMOVAL_FORBIDDEN",
  ADMIN_SUSPENSION_FORBIDDEN = "ADMIN_SUSPENSION_FORBIDDEN",
  SELF_DELETION_FORBIDDEN = "SELF_DELETION_FORBIDDEN",
  BOOTSTRAP_ADMIN_PROTECTED = "BOOTSTRAP_ADMIN_PROTECTED",

  CARD_NOT_FOUND = "CARD_NOT_FOUND",
  CARD_NOT_OWNED = "CARD_NOT_OWNED",
  NO_PACK_AVAILABLE = "NO_PACK_AVAILABLE",
  EMPTY_CATALOG = "EMPTY_CATALOG",
  INVALID_SETTINGS = "INVALID_SETTINGS",

  FAMILY_NOT_FOUND = "FAMILY_NOT_FOUND",
  INVALID_FAMILY_RULE = "INVALID_FAMILY_RULE",

  DISCORD_DISABLED = "DISCORD_DISABLED",
  DISCORD_NOT_LINKED = "DISCORD_NOT_LINKED",
  INVALID_DISCORD_SIGNATURE = "INVALID_DISCORD_SIGNATURE",

  SYNC_RUN_NOT_FOUND = "SYNC_RUN_NOT_FOUND",
  SYNC_ALREADY_RUNNING = "SYNC_ALREADY_RUNNING",

  REALTIME_UNAVAILABLE = "REALTIME_UNAVAILABLE",

  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
}
